function stripMarkdownFences(text = "") {
    return text
        .replace(/```[\s\S]*?```/g, (block) => {
            // remove ```d2 ... ```
            return block.replace(/^```[a-zA-Z0-9]*\n?/, "").replace(/```$/, "");
        })
        .trim();
}

function removeNonD2Text(text = "") {
    // remove leading explanations
    const lines = text.split("\n");

    // Keep only from first "layout:" OR first "direction:" OR first valid id/shape lines
    const startIndex = lines.findIndex((l) => {
        const s = l.trim();
        return (
            s.startsWith("layout:") ||
            s.startsWith("direction:") ||
            s.includes("->") ||
            s.includes("{") ||
            s.match(/^[a-zA-Z0-9_.-]+\s*:/)
        );
    });

    if (startIndex === -1) return text.trim();
    return lines.slice(startIndex).join("\n").trim();
}

function fixStyleKeys(d2 = "") {
    // Convert wrong keys into D2 supported style keys
    const mappings = [
        { from: /^\s*fill\s*:/gm, to: "  style.fill:" },
        { from: /^\s*stroke\s*:/gm, to: "  style.stroke:" },
        { from: /^\s*font-size\s*:/gm, to: "  style.font-size:" },
        { from: /^\s*border-radius\s*:/gm, to: "  style.border-radius:" },
        { from: /^\s*stroke-width\s*:/gm, to: "  style.stroke-width:" },
    ];

    let out = d2;
    for (const m of mappings) out = out.replace(m.from, m.to);
    return out;
}

function removeMermaid(d2 = "") {
    // OpenAI sometimes outputs Mermaid like: graph TD
    return d2.replace(/^\s*graph\s+(TD|LR|RL|BT)\s*$/gim, "").trim();
}

function ensureDefaults(d2 = "") {
    // If layout/direction not present, set defaults at top
    const hasLayout = /^\s*layout\s*:/m.test(d2);
    const hasDirection = /^\s*direction\s*:/m.test(d2);

    let prefix = "";

    if (!hasLayout) prefix += "layout: dagre\n";
    if (!hasDirection) prefix += "direction: right\n";

    // Add a comment header
    prefix += "\n# Generated by BlueprintAI (OpenAI -> D2)\n\n";

    return prefix + d2.trim();
}

function sanitizeD2(raw = "") {
    let d2 = raw;

    d2 = stripMarkdownFences(d2);
    d2 = removeNonD2Text(d2);
    d2 = removeMermaid(d2);
    d2 = fixStyleKeys(d2);
    d2 = d2.replace(/\r/g, "");
    d2 = ensureDefaults(d2);

    return d2.trim() + "\n";
}

module.exports = { sanitizeD2 };
